force-app/main/default/objects/Loan_Repayment_Schedule__c/Loan_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Loan Repayment Schedule</label>
    <nameField>
        <displayFormat>LRP-{0000000000}</displayFormat>
        <label>Loan Repayment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Repayment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Loan_Request__c.field-meta.xml
<CustomField>
    <fullName>Loan_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan  Request</label>
    <referenceTo>Loan_Request__c</referenceTo>
    <relationshipLabel>Loan Repayment Schedules</relationshipLabel>
    <relationshipName>Loan_Repayment_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/Loan_Request__c.object-meta.xml
<CustomObject>
    <label>Loan  Request</label>
    <nameField>
        <displayFormat>LRQ-{0000000000}</displayFormat>
        <label>Loan  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Request__c/fields/Number_Of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Months__c</fullName>
    <label>Number Of Months</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RepaymentScheduleModel.cls
public class RepaymentScheduleModel {
    
    public Loan_Repayment_Schedule__c repaymentSchedule {get;private set;}
    public integer index {get;set;}


    /**
     * @description generateTableData creates a List of RepaymentScheduleModel given a list of repayment records 
     * The general idea is to be able to generate data for the vf wizard (including periods with no payment)
     * @param  repaymentRecords represents the repayment Records to be stored/ already stored in the database
     * @return                  return a List of RepaymentScheduleModel
     */ 
    public static List<RepaymentScheduleModel> generateTableData(List<Loan_Repayment_Schedule__c> repaymentRecords, Loan_Request__c loanRequest) {
        List<RepaymentScheduleModel> response = new List<RepaymentScheduleModel>();
        for(integer i = 1; i < loanRequest.Number_Of_Months__c ; i++){
            


        }


        return response;


    }


}