force-app/main/default/objects/Loan_Repayment_Schedule__c/Loan_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Loan Repayment Schedule</label>
    <nameField>
        <displayFormat>LRP-{0000000000}</displayFormat>
        <label>Loan Repayment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Repayment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Fees</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Loan_Request__c.field-meta.xml
<CustomField>
    <fullName>Loan_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan  Request</label>
    <referenceTo>Loan_Request__c</referenceTo>
    <relationshipLabel>Loan Repayment Schedules</relationshipLabel>
    <relationshipName>Loan_Repayment_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <label>Principal</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/Loan_Request__c.object-meta.xml
<CustomObject>
    <label>Loan  Request</label>
    <nameField>
        <displayFormat>LRQ-{0000000000}</displayFormat>
        <label>Loan  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Request__c/fields/Expected_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Disbursement_Date__c</fullName>
    <label>Expected Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Monthly_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Due_Date__c</fullName>
    <label>Monthly Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Number_Of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Months__c</fullName>
    <label>Number Of Months</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Periods_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Periods_Per_Year__c</fullName>
    <label>Periods Per Year</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Suma_Credit__c.field-meta.xml
<CustomField>
    <fullName>Suma_Credit__c</fullName>
    <label>Suma Credit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RepaymentServiceImplementationA.cls
public with sharing class RepaymentServiceImplementationA 
extends BaseRepaymentServiceImplementation 
implements IRepaymentService{
    
    public RepaymentServiceImplementationA() {
        super();
    }


    /**
     * @description generateRepaymentSchedules houses the logic for the way Loan Repayments 
     * are calculated for this algorithm - For now this uses a basic mock implementation
     * @param  request - represents the Loan Request we are generating repayment schedules for.
     * @return         - returns generated Loan RepaymentSchedules models for display.
     */ 
    public List<Loan_Repayment_Schedule__c> generateRepaymentSchedules(Loan_Request__c request){
        List<Loan_Repayment_Schedule__c> schedules = new List<Loan_Repayment_Schedule__c>();
        List<string> periodsPerYear = request.Periods_Per_year__c.split(';');
        List<RepaymentDatesDecorator> repaymentDates = RepaymentServiceUtils.generateRepaymentDates(request.Expected_Disbursement_Date__c, 
        Integer.valueOf(request.number_Of_Months__c), 
        PeriodsPerYear, Integer.valueOf(request.Monthly_Due_Date__c));

        decimal totalLoanInterest = request.Interest__c * request.Suma_Credit__c / 100;
        for(Integer i =1 ; i <= repaymentDates.size(); i++){
            RepaymentDatesDecorator rpDate = repaymentDates[i-1];
            System.debug(repaymentDate);
            // Loan_Repayment_Schedule__c schedule = new Loan_Repayment_Schedule__c();
            if(rpDate.hasRepayment == true){
                // call a service to calculate the repayment fee
                Loan_Repayment_Schedule__c schedule = new Loan_Repayment_Schedule__c(Date__c = rpDate.repaymentDate ,
                 Principal__c= 5000.00, Interest__c = 400.00, Period__c ='Period '+i, Total_Amount__c = 8012.3 ,
                 Fees__c=200.00);
                
                schedules.add(schedule);    
            }

        }
        return schedules;

    }



}