force-app/main/default/objects/Loan_Offer__c/Loan_Offer__c.object-meta.xml
<CustomObject>
    <description>Represents a Loan Offer</description>
    <label>Loan Offer</label>
    <nameField>
        <label>Loan Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Offer__c/fields/Administrative_Fee__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Fee__c</fullName>
    <label>Administrative Fee</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Offer__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <description>Represents  the standard interest rate on this loan offer.</description>
    <label>Interest</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Offer__c/fields/Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fee__c</fullName>
    <label>Processing Fee</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/Loan_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Loan Repayment Schedule</label>
    <nameField>
        <displayFormat>LRP-{0000000000}</displayFormat>
        <label>Loan Repayment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Repayment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Loan_Request__c.field-meta.xml
<CustomField>
    <fullName>Loan_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan  Request</label>
    <referenceTo>Loan_Request__c</referenceTo>
    <relationshipLabel>Loan Repayment Schedules</relationshipLabel>
    <relationshipName>Loan_Repayment_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Payment</fullName>
                <default>true</default>
                <label>Awaiting Payment</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Request__c/Loan_Request__c.object-meta.xml
<CustomObject>
    <label>Loan  Request</label>
    <nameField>
        <displayFormat>LRQ-{0000000000}</displayFormat>
        <label>Loan  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Request__c/fields/Expected_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Disbursement_Date__c</fullName>
    <label>Expected Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Loan_Offer__c.field-meta.xml
<CustomField>
    <fullName>Loan_Offer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan Offer</label>
    <referenceTo>Loan_Offer__c</referenceTo>
    <relationshipLabel>Loan Requests</relationshipLabel>
    <relationshipName>Loan_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Monthly_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Due_Date__c</fullName>
    <label>Monthly Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Number_Of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Months__c</fullName>
    <label>Number Of Months</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Periods_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Periods_Per_Year__c</fullName>
    <label>Periods Per Year</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Risk_Fee__c.field-meta.xml
<CustomField>
    <fullName>Risk_Fee__c</fullName>
    <label>Risk Fee</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Request__c/fields/Suma_Credit__c.field-meta.xml
<CustomField>
    <fullName>Suma_Credit__c</fullName>
    <label>Suma Credit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RepaymentServiceImpl__mdt/RepaymentServiceImpl__mdt.object-meta.xml
<CustomObject>
    <label>RepaymentServiceImpl</label>
    <pluralLabel>RepaymentServiceImpl</pluralLabel>
</CustomObject>

force-app/main/default/objects/RepaymentServiceImpl__mdt/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RepaymentGeneratorWizardController.cls
public without sharing class RepaymentGeneratorWizardController {
    
    private List<String> fieldsOfInterest = new List<String>{'Suma_Credit__c','Number_Of_Months__c',
    'Monthly_Due_Date__c' ,'Name','Status__c' ,'Expected_Disbursement_Date__c', 'Periods_Per_Year__c',
    'Interest__c','Processing_Fee__c' ,'Risk_Fee__c','Administrative_Fee__c','Loan_Offer__r.Id'
    ,'Loan_Offer__r.Interest__c','Loan_Offer__r.Risk_Fee__c','Loan_Offer__r.Administrative_Fee__c',
    'Loan_Offer__r.Processing_Fee__c'
    };
    private Loan_Request__c loanRequest ; 
    private IRepaymentService rPayService {get;set;}
    private List<string> acceptableStatuses = new String[]{'Approved' ,'Disbursed'};


    public boolean messageDisplayed {get;set;}
    public boolean displayContent {get;set;}
    public string implementation {get;set;}
    public List<RepaymentScheduleModel> GeneratedRepayments {get;set;}
    public List<SelectOption> implementationOptions {get
        {
            List<SelectOption> options = new List<SelectOption>();
            Map<string,RepaymentServiceImpl__mdt> registeredRepaymentServices = RepaymentServiceImpl__mdt.getAll();
            if(registeredRepaymentServices != null && registeredRepaymentServices.size() > 0){
                for(RepaymentServiceImpl__mdt mdt : registeredRepaymentServices.values()){
                    SelectOption opt = new SelectOption(mdt.ServiceName__c , mdt.ServiceName__c);
                    options.add(opt);
                }
            }
            return options;
        }set;}

        public boolean disableAction{get{
            return this.rPayService == null ? true : false;
         }set;}





    
    public RepaymentGeneratorWizardController(ApexPages.StandardController std) {
        if(!Test.isRunningTest()){
            std.addFields(fieldsOfinterest);
        }
        loanRequest = (Loan_Request__c)std.getRecord();
        displayContent = true;
        implementation = implementationOptions[0].getValue();
        onChangeImplementation();
        if(! (loanRequest?.Status__c== null) &&  !(acceptableStatuses.contains(loanRequest.Status__c))){
            displayContent = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR , 'You cannot Generate Repayment Schedules for Loans Not yet Approved Or Disbursed. Please Approve/Disburse This Loan ')); 
        }
    }

    public void onChangeImplementation(){
        try{
            this.rPayService = (IRepaymentService)RepaymentServiceFactory.getInstance(implementation);
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR , 'No Registered Implementation Found For the Selected Service'));
        }

    }

    public void onGenerateRepaymentSchedules(){
        List<Loan_Repayment_Schedule__c> repaymentSchedules = this.rPayService.generateRepaymentSchedules(this.loanRequest);
        this.GeneratedRepayments = RepaymentScheduleModel.generateTableData(repaymentSchedules, this.loanRequest);
    }

    public void SaveGeneratedRepaymentSchedules(){

    }



}